### ISSUE TITLE
request with array returning error MySQL error 1054: Unknown column 'Array' in 'where clause'

### ISSUE THREAD

**Issue by aryeharmon** [jclo/jsugar#1]
if i make a request with an array field, example:

```
        var params = {
            session: id,
            module_name: 'blahblah',
            select_fields: [
                'id',
                'name',
            ],
        };
jsugar.call(domain, 'get_entry_list', params, function(error, res) {
```

i will get the following sugarcrm error: MySQL error 1054: Unknown column 'Array' in 'where clause'

apparently the requests are not sent out right when there is an array field.

**Comment by jclo** [comment]
@aryeharmon 
SugarCRM API requires to fulfil all the parameters. As sugar is a low level API, it doesn't fill the holes. So, you should do this (and match this sequence):

var params = {
    session: id,
    module_name: 'Accounts',
    query: '',
    order_by: '',
    offset: 0,
    select_fields: ['name'],
    link_name_to_fields_array: [],
    max_results: 20,
    deleted: false,
    favorites: false
  };
  jsugar.call(domain, 'get_entries_list', params, function(error, res) {
